[project]
name = "language-extraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.75.0",
    "grpcio-tools>=1.75.0",
    "langextract>=1.0.9",
    "requests>=2.32.5",
]
