# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lang_extract.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lang_extract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12lang_extract.proto\x12\x0flang_extract.v2\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x86\x02\n\x0bLangExtract\x12H\n\x08SayHello\x12\x1d.lang_extract.v2.HelloRequest\x1a\x1b.lang_extract.v2.HelloReply\"\x00\x12U\n\x13SayHelloStreamReply\x12\x1d.lang_extract.v2.HelloRequest\x1a\x1b.lang_extract.v2.HelloReply\"\x00\x30\x01\x12V\n\x12SayHelloBidiStream\x12\x1d.lang_extract.v2.HelloRequest\x1a\x1b.lang_extract.v2.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lang_extract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=39
  _globals['_HELLOREQUEST']._serialized_end=67
  _globals['_HELLOREPLY']._serialized_start=69
  _globals['_HELLOREPLY']._serialized_end=98
  _globals['_LANGEXTRACT']._serialized_start=101
  _globals['_LANGEXTRACT']._serialized_end=363
# @@protoc_insertion_point(module_scope)
